<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, jQuery Slider Easing, jQuery Slider Values" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="resource/engine1/style.css" media="screen" />
	<style type="text/css">a#vlb{display:none}</style>
	<script type="text/javascript" src="resource/engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#ffffff">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images">
<a href="#"><img src="resource/data1/images/climber.jpg" alt="climber" title="climber" id="wows0"/></a>
<a href="#"><img src="resource/data1/images/loggy.jpg" alt="loggy" title="loggy" id="wows1"/></a>
<a href="#"><img src="resource/data1/images/dustermountain.jpg" alt="DusterMountain" title="DusterMountain" id="wows2"/></a>
<a href="#"><img src="resource/data1/images/renault.jpg" alt="renault" title="renault" id="wows3"/></a>
<a href="#"><img src="resource/data1/images/tata.jpg" alt="tata" title="tata" id="wows4"/></a>
</div>
<div class="ws_bullets"><div>
<a href="#wows0" title="climber"><img src="resource/data1/tooltips/climber.jpg" alt="climber"/>1</a>
<a href="#wows1" title="loggy"><img src="resource/data1/tooltips/loggy.jpg" alt="loggy"/>2</a>
<a href="#wows2" title="DusterMountain"><img src="resource/data1/tooltips/dustermountain.jpg" alt="DusterMountain"/>3</a>
<a href="#wows3" title="renault"><img src="resource/data1/tooltips/renault.jpg" alt="renault"/>4</a>
<a href="#wows4" title="tata"><img src="vdata1/tooltips/tata.jpg" alt="tata"/>5</a>
</div></div>
<a style="display:none" href="http://wowslider.com">jQuery Slider Plugins by WOWSlider.com v1.7</a>
	</div>
	<script type="text/javascript" src="resource/engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>